TARGET = circle celsius2fahr fahr2celsius fahr2celsius2 fahr2celsius3 limits literal score triangle


all: ${TARGET}

circle: $@ 

celsius2fahr: $@

fahr2celsius: $@

fahr2celsius2:$@

fahr2celsius3: $@

limits: $@

literal: $@

score: $@

triangle: $@

clean:
	rm -f ${TARGET} celsius2fahr